### ISSUE TITLE
You require 'tweetnacl' but don't compile it in package.json

### ISSUE THREAD

**Issue by kalepail** [stellarport/stellar-keystore#4]
![Screen Shot 2019-04-11 at 4 49 08 PM](https://user-images.githubusercontent.com/4383610/55992095-bc368a80-5c79-11e9-8c6d-c431384c05f8.png)

**Comment by kalepail** [comment]
As a friendly note it's helpful to mention the PR or commit which closed the issue. Thanks!
3f50aaa7d47e168daf03d4c0457e168613755de4

**Comment by istrau2** [comment]
@tyvdh Sorry, I used the #Fixed commit message. It looks like it says the commit just above. Does it not for you?

**Comment by kalepail** [comment]
I do see that. I'm blind. Ignore me. Carry on. ✌️
